output_db_path: "song_master.sqlite"
schema_version: "33"
chart_id_missing_policy: "error"
music_alias_manual_csv_path: "data/music_alias_manual.csv"

github:
  owner: "tts1374"
  repo: "iidx_all_songs_master"
  upload_to_release: true
  require_previous_release: true
  asset_name: "song_master.sqlite"
